---
title: "participant data"
author: "Katrina Li"
date: "10/07/2021"
output: html_document
---
```{r User define}
# Please change this configuration
require("knitr")
opts_knit$set(root.dir = "/Users/kechun/Documents/GitHub/PerMaSC/data")
```


```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
stimulim <- read.csv("data/stimulim.csv",header = T)
```

```{r}
clean <- function(data){
  data <- data %>%
    pivot_wider(
    id_cols = sentence,
    names_from = label,
    values_from = time,
  ) %>%
  separate(sentence, into = c('number','audio','video'), sep = "(a|v)(?=M|NM)") %>%
  mutate(
    dur = r-b,
    audio = paste0("a",audio),
    video = paste0("v",video),
    sentence_label = paste(number, audio, sep="_")
  )
 data <- data %>%
   left_join(stimulim) %>%
  select(number, audio, video, sentence_label, r, dur, length1, length2, length3) %>%
  mutate(
    react1 = dur - length1,
    react2 = dur - length2,
    react3 = dur - length3,
    type = paste0(audio,video),
    context = str_sub(number,-1,-1)
  )  %>%
  filter(!(number== "101L" & type == "aMvM")) %>%
  filter(!(number== "48L" & type == "aNMvM")) %>%
  filter(!(number== "44L" & type == "aNMvNM")) %>%
  filter(!(number== "45H" & type == "aMvNM")) %>%
  filter(!(number== "13H" & type == "aMvM")) %>%
  filter(!(number== "102L" & type == "aNMvM")) %>%
  filter(!(number== "55H" & type == "aNMvNM")) %>%
  filter(!(number== "52H" & type == "aMvNM"))
}
clean2 <- function(data){
  data <- data %>%
    pivot_wider(
    id_cols = sentence,
    names_from = label,
    values_from = time,
  ) %>%
  mutate(
    sentence = str_sub(sentence,10,-1)
  )%>%
  separate(sentence, into = c('number','audio','video'), sep = "(a|v)(?=M|NM)") %>%
  mutate(
    dur = r-b,
    audio = paste0("a",audio),
    video = paste0("v",video),
    sentence_label = paste(number, audio, sep="_")
  )
 data <- data %>%
   left_join(stimulim) %>%
  select(number, audio, video, sentence_label, r, dur, length1, length2, length3) %>%
  mutate(
    react1 = dur - length1,
    react2 = dur - length2,
    react3 = dur - length3,
    type = paste0(audio,video),
    context = str_sub(number,-1,-1)
  )  %>%
  filter(!(number== "101L" & type == "aMvM")) %>%
  filter(!(number== "48L" & type == "aNMvM")) %>%
  filter(!(number== "44L" & type == "aNMvNM")) %>%
  filter(!(number== "45H" & type == "aMvNM")) %>%
  filter(!(number== "13H" & type == "aMvM")) %>%
  filter(!(number== "102L" & type == "aNMvM")) %>%
  filter(!(number== "55H" & type == "aNMvNM")) %>%
  filter(!(number== "52H" & type == "aMvNM"))
}
nooutlier <- function(x){
  x[!x %in% boxplot.stats(x)$out]
}
```


```{r}
c1 <- read.delim("data/Abby.txt",header = T,sep = "\t")
c1 <- clean(c1)
write.table
```
```{r}
# raw data


c1 %>%
  ggplot(aes(x=type, y=react3, fill = context)) +
  geom_bar(position = "dodge", stat = "summary") + 
  geom_jitter()

c1 %>%
  ggplot(aes(x=type, y=react3, fill = context)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 1) + 
  geom_jitter(width = 0.2)
ggsave("figure/c1.png")
# remove outliers
```

```{r}
a1 <- read.delim("data/a1.txt",header = T,sep = "\t")
a1 <- clean(a1)

a1 %>%
  ggplot(aes(x=video, y=react3, fill = audio)) +
  geom_bar(position = "dodge", stat = "summary") + 
  geom_jitter()


a1 %>%
  ggplot(aes(x=type, y=react3, fill = context)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 1) + 
  geom_jitter(width = 0.2)
ggsave("figure/a1.png")
```

```{r 210719_a25measure}
a25 <- read.delim("data/210719_a25measure.txt",header = T,sep = "\t")

a25 <- clean2(a25)


a25 %>%
  ggplot(aes(x=type, y=react3)) +
  geom_point(aes(colour = context),position = position_jitterdodge(dodge.width = 0.9),alpha = 0.5)+
  geom_boxplot(aes(colour = context), outlier.colour = "black", outlier.shape = 1, position = position_dodge(width=0.9))

ggsave("figure/a25.png")
```

