---
title: "Descriptive Statistics and Plots"
author: "Julia Schwarz"
date: "28/10/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Packages

```{r packages, include=FALSE}
library(lme4)
library(ggplot2)
library(lattice)
library(car)
library(lmerTest)
library(moments)
library(rcompanion)
library(MuMIn)
library(Hmisc)
library(dplyr)
library(stargazer)
library(see) 
```



## Data File

Pre-processed data file (critical items only), outliers, fillers, practice, etc. removed. 3560 observations. 

```{r load data, echo=FALSE}
data<-read.delim(file.choose(), header=T)
```



## Variable Prep

```{r variables, echo=FALSE}

# Random 
data$SUBJECT <- as.factor(data$SUBJECT)
data$ITEM <- as.factor(data$ITEM)

# Outcome Var
data$RT <- as.numeric(data$RT) #RT from the end of the sentence

# Fixed
data$GROUP <- factor(data$GROUP, levels = c("a","c"), labels = c("Adults", "Children"))
data$AUDIO <- factor(data$AUDIO, levels = c("aNM","aM"), labels = c("No Mask", "Mask")) 
data$Acoustic <- data$AUDIO
data$VISUAL <- factor(data$VISUAL, levels = c("vNM","vM"), labels = c("No Mask", "Mask"))
data$PREDICTABILITY <- factor(data$PREDICT, levels = c("H","L"), labels = c("High", "Low"))
#data$TRIALORDER <- as.numeric(data$TRIALORDER)

# Other
data$ACC <- as.factor(data$ACC) #1==correct
data$CONDITION_old <- as.factor(data$CONDITION)
data$CONDITION <- factor(data$CONDITION, levels = c("aNMvNM","aNMvM","aMvNM","aMvM"), labels = c("1","2","3","4"))
#data$BLOCK <- as.factor(data$BLOCK)
#data$LIST <- as.factor(data$Experiment_version)

data$TARGET <- as.factor(data$ITEM)
data$TARGET <- gsub('.{1}$', '', data$TARGET)

```


## Subsets

```{r subsets, include=FALSE}

adults <- subset(data, data$GROUP == 'Adults') #1808
children <- subset(data, data$GROUP == 'Children') #1752

```


## Overview of All Conditions

```{r all conditions}

ggplot(data, aes(CONDITION, RT, colour=PREDICTABILITY)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1))+
  theme_classic() +
  stat_summary(fun = mean, geom = "point", size = 3, position = position_dodge(0.1)) +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6, aes(group = PREDICTABILITY),position = position_dodge(0.1)) +
  labs(x = "Visual-Acoustic Conditions", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 10), # angle = 20; for x label text
        axis.title.x = element_text(size = 12), # for x axis title
        axis.title.y = element_text(size = 10), # for y-axis title 
        strip.text.x = element_text(size = 12), # for sub-title of the figure
#        legend.text = element_text(size=0), # for legend size
#        legend.title = element_text(size=0), # for legend title
        ) +
  theme(aspect.ratio=1/1) +
  scale_color_manual(values=c('#006633','#CC8800')) # color palette

```

## Visual Effect

```{r vis ef}

ggplot(data, aes(VISUAL, RT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               colour='#666666') +
  stat_summary(fun = mean, geom = "point", size = 3, colour=('#666666')) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6, colour='#666666', aes(group = 1)) +
  labs(x = "Visual Mask Effect Only", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 10), # for x label text
        axis.title.x = element_text(size = 12), # for x axis title
        axis.title.y = element_text(size = 10),
        strip.text.x = element_text(size = 12))

```

## Acoustic Effect

```{r ac ef}

ggplot(data, aes(AUDIO, RT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               colour='#666666') +
  stat_summary(fun = mean, geom = "point", size = 3, colour=('#666666')) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6, colour='#666666', aes(group = 1)) +
  labs(x = "Acoustic Mask Effect Only", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 10), # for x label text
        axis.title.x = element_text(size = 12), # for x axis title
        axis.title.y = element_text(size = 10),
        strip.text.x = element_text(size = 12))

```

## Predictability Effect

```{r pred ef}

ggplot(data, aes(PREDICTABILITY, RT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               colour='#666666') +
  stat_summary(fun = mean, geom = "point", size = 3, colour=('#666666')) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6, colour='#666666', aes(group = 1)) +
  labs(x = "Predictability Effect Only", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 10), # for x label text
        axis.title.x = element_text(size = 12), # for x axis title
        axis.title.y = element_text(size = 10),
        strip.text.x = element_text(size = 12))

```

# Acoustic x Visual Mask Interaction

```{r inter 1}

ggplot(data, aes(VISUAL, RT, colour=Acoustic)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1) ) +
  stat_summary(fun = mean, geom = "point",size = 3,position = position_dodge(0.1)) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6,aes(group = Acoustic), position = position_dodge(0.1)) +
  labs(x = "Visual", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 20), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15), # for y axis title
        strip.text.x = element_text(size = 20), # for sub-title of the figure
        legend.text = element_text(size=15), # for legend size
        legend.title = element_text(size=15), # for legend title
        )+ # for y-axis title 
  scale_color_manual(values=c('#666666', "#CC0066")) # color palette

```

## Acoustic x Predictability Mask Interaction

```{r inter 2}

ggplot(data, aes(PREDICTABILITY, RT, colour=Acoustic)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1) ) +
  stat_summary(fun = mean, geom = "point",size = 3,position = position_dodge(0.1)) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6,aes(group = Acoustic), position = position_dodge(0.1)) +
  labs(x = "Predictability", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 20), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15), # for y axis title
        strip.text.x = element_text(size = 20), # for sub-title of the figure
        legend.text = element_text(size=15), # for legend size
        legend.title = element_text(size=15), # for legend title
        )+ # for y-axis title 
  scale_color_manual(values=c('#666666', "#CC0066")) # color palette

```


# Acoustic x Visual Mask x Predict x Group

```{r inter 1}

ggplot(data, aes(VISUAL, RT, colour=Acoustic)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1) ) +
  stat_summary(fun = mean, geom = "point",size = 3,position = position_dodge(0.1)) +
  theme_classic() +
  facet_grid(cols = vars(GROUP, PREDICTABILITY)) +
  stat_summary(fun =mean, geom="line", size = 0.6,aes(group = Acoustic), position = position_dodge(0.1)) +
  labs(x = "Visual", y = "Mean Reaction Times in ms") +
  ggtitle("Predictability (High/Low) by Group") +
  theme(axis.text.x = element_text(size = 12, angle=15), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 10), # for y axis title
        strip.text.x = element_text(size = 15), # for sub-title of the figure
        legend.text = element_text(size=15), # for legend size
        legend.title = element_text(size=15), # for legend title
        )+ # for y-axis title 
  theme(aspect.ratio=1.5/1) +
  scale_color_manual(values=c('#666666', "#CC0066")) # color palette


```


