---
title: "Data cleaning (first batch -- 17 files)"
author: "Katrina Li"
date: "28/10/2021"
output: html_document
---
```{r}
try <- read.delim("datafile_first_batch/210725_a120timep2.txt",sep="\t",check.names = F)
```

```{r first batch, include=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
path <- "datafile_first_batch"
timep1files <- list.files(path,pattern = "p1.txt",full.names = T)
timep2files <- list.files(path,pattern = "p2.txt",full.names = T)

p1files <-tibble(File = timep1files) %>%
  extract(File, "parid","([0-9]{6}_[A-Za-z0-9]*time)",remove = FALSE) %>%
  mutate(Data = lapply(File, read.delim, sep = "\t")) %>%
  unnest(Data)%>%
  select(-File)%>%
  mutate(label = str_replace_all(label,"\\.","")) %>% # Replace extra '.' symbol at the end
  mutate(label = str_replace_all(label,"\\_$","")) # Replace extra '_' symbol at the end

p2files <-tibble(File = timep2files) %>%
  extract(File, "parid","([0-9]{6}_[A-Za-z0-9]*time)",remove = FALSE) %>%
  mutate(Data = lapply(File, read.delim, sep = "\t",check.names = F)) %>%
  unnest(Data) %>%
  select(-File) %>%
  mutate(label = str_replace_all(label,"\\.",""))%>%
  mutate(label = str_replace_all(label,"\\_$","")) 

stimulim <- read.csv("datafile_first_batch/stimulim.csv",header = T)

#c29timep2, a120timep1&a120 timep2 have encoding problems. 
# Solution: open the file in Numbers, copy it to excel, and save as tab-delimited file txt

# Other possible errors: by using 'separte' failes below, you will be able to see 
combine <- p1files %>% 
  pivot_wider(
    names_from = timetype,
    values_from = timepoint,
  ) %>%
  mutate(
    duration1 = rstart-b
  ) %>%
  inner_join(p2files, by = c("parid","label")) %>% #anti_join could see which files are not matched
  mutate(
    beep_response = duration1 + duration2
  ) %>%
  separate(note, into=c("accuracy", "note"), sep="(?<=[0-1])_") %>%
  separate(label, into=c("scheduleID", "sentence"), sep = "_") %>% 
  separate(sentence, into = c('number','audio','video'), sep = "(a|v)(?=M|NM)") %>%
  mutate(
    note = str_replace_all(note,"^_",""), # Replace extra '_' symbol in the note
    video = str_replace_all(video, "[a-z]$","")
  )%>%
  mutate(
    audio = paste0("a",audio),
    video = paste0("v",video),
    sentence_label = paste(number, audio, sep="_")
  ) %>%
  left_join(stimulim, by = c("sentence_label","number")) %>%
  mutate(
    react1 = (beep_response - length1)*1000,
    react2 = (beep_response - length2)*1000,
    type = paste0(audio,video),
    context = str_sub(number,-1,-1),
    parid = str_sub(parid, 1, nchar(parid)-4),
    group = str_extract(parid,"(?<=_)[a,c]"),
    #group = recode(group,a="adult",c="child")
  )  %>%
  select(parid, scheduleID, react1, react2,accuracy, note, number, correctans,audio, video, context, group, type, beep_response, length1, length2) 

write.csv(combine,"firstbatch.csv",row.names = FALSE)

```

```{r second batch}

path <- "datafile_second_batch"
timep1files <- list.files(path,pattern = "p1.txt",full.names = T)
timep2files <- list.files(path,pattern = "p2.txt",full.names = T)

p1files <-tibble(File = timep1files) %>%
  extract(File, "parid","([0-9]{6}_[A-Za-z0-9]*time)",remove = FALSE) %>%
  mutate(Data = lapply(File, read.delim, sep = "\t")) %>%
  unnest(Data)%>%
  select(-File)%>%
  mutate(label = str_replace_all(label,"\\.","")) %>% # Replace extra '.' symbol at the end
  mutate(label = str_replace_all(label,"\\_$","")) # Replace extra '_' symbol at the end

p2files <-tibble(File = timep2files) %>%
  extract(File, "parid","([0-9]{6}_[A-Za-z0-9]*time)",remove = FALSE) %>%
  mutate(Data = lapply(File, read.delim, sep = "\t",check.names = F)) %>%
  unnest(Data) %>%
  select(-File) %>%
  mutate(label = str_replace_all(label,"\\.",""))%>%
  mutate(label = str_replace_all(label,"\\_$","")) 

stimulim <- read.csv("datafile_first_batch/stimulim.csv",header = T)

#c29timep2, a120timep1&a120 timep2 have encoding problems. 
# Solution: open the file in Numbers, copy it to excel, and save as tab-delimited file txt

# Other possible errors: by using 'separte' failes below, you will be able to see 
combine <- p1files %>% 
  pivot_wider(
    names_from = timetype,
    values_from = timepoint,
  ) %>%
  mutate(
    duration1 = rstart-b
  ) %>%
  inner_join(p2files, by = c("parid","label")) %>% #anti_join could see which files are not matched
  mutate(
    beep_response = duration1 + duration2
  ) %>%
  separate(note, into=c("accuracy", "note"), sep="(?<=[0-1])_") %>%
  separate(label, into=c("scheduleID", "sentence"), sep = "_") %>% 
  separate(sentence, into = c('number','audio','video'), sep = "(a|v)(?=M|NM)") %>%
  mutate(
    note = str_replace_all(note,"^_",""), # Replace extra '_' symbol in the note
    video = str_replace_all(video, "[a-z]$","")
  )%>%
  mutate(
    audio = paste0("a",audio),
    video = paste0("v",video),
    sentence_label = paste(number, audio, sep="_")
  ) %>%
  left_join(stimulim, by = c("sentence_label","number")) %>%
  mutate(
    react1 = (beep_response - length1)*1000,
    react2 = (beep_response - length2)*1000,
    type = paste0(audio,video),
    context = str_sub(number,-1,-1),
    parid = str_sub(parid, 1, nchar(parid)-4),
    group = str_extract(parid,"(?<=_)[a,c]"),
    #group = recode(group,a="adult",c="child")
  )  %>%
  select(parid, scheduleID, react1, react2,accuracy, note, number, correctans,audio, video, context, group, type, beep_response, length1, length2) 

write.csv(combine,"secondbatch.csv",row.names = FALSE)
```


# Trial order & Questionnaire file

```{r}
data1 <- read.csv("firstbatch.csv",header = T)
data2 <- read.csv("secondbatch.csv", header = T)
fulldata <- rbind(data1,data2)

fulldata <- fulldata %>%
    mutate(
    videoname = paste(number, audio, video, sep="_"),
    videoname = paste(videoname,".mp4",sep = "")
  )

trial_adult <- read.csv("questionnaire/adult_trial.csv", header = T)
trial_child <- read.csv("questionnaire/child_trial.csv", header = T)
trial <- rbind(trial_adult, trial_child)

Qadult <- read.csv("Qadult.csv", header = T)
Qchild <- read.csv("Qchild.csv", header = T)
Qall <- rbind(Qadult, Qchild)

mergedata <- fulldata %>%
  left_join(trial, by = c("parid" = "Participant.Public.ID","videoname" = "videoname")) %>%
  left_join(Qall, by = c("parid"="Participant.Public.ID")) %>%
  mutate(
      block = case_when(row_number <=30 ~ 1,
                      row_number >30 & row_number <=60 ~ 2,
                      row_number >60 & row_number <=90 ~ 3,
                      row_number >90 ~4)
  )
```

# Basic Examination
```{r}
# Check the merge is sucessful
fulldata %>%
  anti_join(trial, by = c("parid" = "Participant.Public.ID","videoname" = "videoname")) 

# checking the number of NA for each column
# trial doesn't have weird single NA value
# Qall doesn't have weird single NA value
# full doesn't have weird single NA value
cbind(
   lapply(
     lapply(mergedata, is.na)
     , sum)
   )
# Some variables has weird one NA where they shouldn't be
# Two sources of problem: adult, child questionnaire not exporting correctly; one strange data point in the check file
#210723_a79 full data has 134H_aNM_vM.mp4 not in the full data file!
# Go back and remove two Qs from the questionnaire: languages.text & mask.problems.text

# CHeck the range of block and trial, max.trial should be 120
# It is just possible that not all of the participants go over all stimuli
mergedata %>%
  group_by(parid) %>%
  summarise(max = max(row_number), n = n())

trial %>%
  group_by(Participant.Public.ID) %>%
  summarise(max = max(row_number), n = n())

#210725_a120 has 93LaMvNM as 121th -129 rows! two 25L!!!
#full data has alright
#it's trial's data fault - jsut two links - remove duplicates in python

trial %>%
  filter(Participant.Public.ID == "210725_a120") %>%
  filter(videoname == "25L_aM_vM.mp4") %>%
  select(filename)


```


# Write the file
```{r read and generate full data}
nrow(mergedata)
colnames(mergedata)
write.csv(mergedata,"fulldata.csv",row.names = FALSE)
```


