---
title: "Data cleaning (first batch -- 17 files)"
author: "Katrina Li"
date: "28/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
#path <- "datafile_first_batch"
path <- "datafile_second_batch"
timep1files <- list.files(path,pattern = "p1.txt",full.names = T)
timep2files <- list.files(path,pattern = "p2.txt",full.names = T)

p1files <-tibble(File = timep1files) %>%
  extract(File, "parid","([0-9]{6}_[A-Za-z0-9]*time)",remove = FALSE) %>%
  mutate(Data = lapply(File, read.delim, sep = "\t")) %>%
  unnest(Data)%>%
  select(-File)%>%
  mutate(label = str_replace_all(label,"\\.","")) %>% # Replace extra '.' symbol at the end
  mutate(label = str_replace_all(label,"\\_$","")) # Replace extra '_' symbol at the end

p2files <-tibble(File = timep2files) %>%
  extract(File, "parid","([0-9]{6}_[A-Za-z0-9]*time)",remove = FALSE) %>%
  mutate(Data = lapply(File, read.delim, sep = "\t",check.names = F)) %>%
  unnest(Data) %>%
  select(-File) %>%
  mutate(label = str_replace_all(label,"\\.",""))%>%
  mutate(label = str_replace_all(label,"\\_$","")) 

stimulim <- read.csv("datafile_first_batch/stimulim.csv",header = T)

#c29timep2, a120timep1&a120 timep2 have encoding problems. 
# Solution: open the file in Numbers, copy it to excel, and save as tab-delimited file txt

# Other possible errors: by using 'separte' failes below, you will be able to see 
combine <- p1files %>% 
  pivot_wider(
    names_from = timetype,
    values_from = timepoint,
  ) %>%
  mutate(
    duration1 = rstart-b
  ) %>%
  inner_join(p2files, by = c("parid","label")) %>% #anti_join could see which files are not matched
  mutate(
    beep_response = duration1 + duration2
  ) %>%
  separate(note, into=c("accuracy", "note"), sep="(?<=[0-1])_") %>%
  separate(label, into=c("scheduleID", "sentence"), sep = "_") %>% 
  separate(sentence, into = c('number','audio','video'), sep = "(a|v)(?=M|NM)") %>%
  mutate(
    note = str_replace_all(note,"^_",""), # Replace extra '_' symbol in the note
    video = str_replace_all(video, "[a-z]$","")
  )%>%
  mutate(
    audio = paste0("a",audio),
    video = paste0("v",video),
    sentence_label = paste(number, audio, sep="_")
  ) %>%
  left_join(stimulim, by = c("sentence_label","number")) %>%
  mutate(
    react1 = (beep_response - length1)*1000,
    react2 = (beep_response - length2)*1000,
    type = paste0(audio,video),
    context = str_sub(number,-1,-1),
    parid = str_sub(parid, 1, nchar(parid)-4),
    group = str_extract(parid,"(?<=_)[a,c]"),
    #group = recode(group,a="adult",c="child")
  )  %>%
  select(parid, scheduleID, react1, react2,accuracy, note, number, correctans,audio, video, context, group, type, beep_response, length1, length2) 

#write.csv(combine,"firstbatch.csv",row.names = FALSE)
write.csv(combine,"secondbatch.csv",row.names = FALSE)

```

```{r}
data1 <- read.csv("firstbatch.csv",header = T)
data2 <- read.csv("secondbatch.csv", header = T)
fulldata <- rbind(data1,data2)
write.csv(fulldata,"fulldata.csv",row.names = FALSE)
```


