---
title: "plotting"
author: "Katrina Li"
date: "02/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Variable Prep

```{r variables, include=FALSE}
library(lme4)
library(ggplot2)
library(lattice)
library(car)
library(lmerTest)
library(moments)
library(rcompanion)
library(MuMIn)
library(Hmisc)
library(dplyr)
library(stargazer)
library(see) 
data<-read.delim("211029_subset_data_cleaned.txt", header=T)
# Random 
data$SUBJECT <- as.factor(data$SUBJECT)
data$ITEM <- as.factor(data$ITEM)

# Outcome Var
data$RT <- as.numeric(data$RT) #RT from the end of the sentence

# Fixed
data$GROUP <- factor(data$GROUP, levels = c("a","c"), labels = c("Adults", "Children"))
data$AUDIO <- factor(data$AUDIO, levels = c("aM","aNM"), labels = c("Mask", "No Mask")) 
data$VISUAL <- factor(data$VISUAL, levels = c("vM","vNM"), labels = c("Mask", "No Mask"))
data$PREDICT <- factor(data$PREDICT, levels = c("H","L"), labels = c("High", "Low"))
#data$TRIALORDER <- as.numeric(data$TRIALORDER)

# Other
data$ACC <- as.factor(data$ACC) #1==correct
data$CONDITION <- as.factor(data$CONDITION)
#data$BLOCK <- as.factor(data$BLOCK)
#data$LIST <- as.factor(data$Experiment_version)

```

```{r simple comparison plots, echo=TRUE}
# Summary plots

ggplot(data, aes(PREDICT, RT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
  ) +
  stat_summary(fun = mean, geom = "point", size = 3) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line",size = 0.6, aes(group = 1)) +
  ggtitle("Reaction times by Group and Predictability") +
  labs(x = "Predict", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 15), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15),
        strip.text.x = element_text(size = 20) # for sub-title of the figure
        ) # for y-axis title 


ggplot(data, aes(VISUAL, RT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
  ) +
  stat_summary(fun = mean, geom = "point", size = 3) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6, aes(group = 1)) +
  ggtitle("Reaction times by Group and Visual Mask Effect") +
  labs(x = "Visual", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 15), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15),
        strip.text.x = element_text(size = 20) # for sub-title of the figure
        ) # for y-axis title 


ggplot(data, aes(AUDIO, RT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
  ) +
  stat_summary(fun = mean, geom = "point", size = 3) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6,aes(group = 1)) +
  ggtitle("Reaction times by Group and Acoustic Mask Effect") +
  labs(x = "Audio", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 15), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15),
        strip.text.x = element_text(size = 20) # for sub-title of the figure
        ) # for y-axis title 

# Auditory * Predictability
ggplot(data, aes(PREDICT, RT, colour=AUDIO)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1)
  ) +
  stat_summary(fun = mean, geom = "point",size = 3,position = position_dodge(0.1)) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6,aes(group = AUDIO), position = position_dodge(0.1)) +
  ggtitle("Reaction times by Audio X Predict Mask Interaction") +
  labs(x = "Predict", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 20), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15), # for y axis title
        strip.text.x = element_text(size = 20), # for sub-title of the figure
        legend.text = element_text(size=15), # for legend size
        legend.title = element_text(size=15), # for legend title
        )+ # for y-axis title 
  scale_color_manual(values=c("#0072B2", "#D55E00")) # color palette


# Auditory * Visual
ggplot(data, aes(VISUAL, RT, colour=AUDIO)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1)
  ) +
  stat_summary(fun = mean, geom = "point",size = 3,position = position_dodge(0.1)) +
  theme_classic() +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6,aes(group = AUDIO),position = position_dodge(0.1)) +
  ggtitle("Reaction times by Audio X Visual Mask Interaction") +
  labs(x = "Visual", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 20), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15), # for y axis title
        strip.text.x = element_text(size = 20), # for sub-title of the figure
        legend.text = element_text(size=15), # for legend size
        legend.title = element_text(size=15), # for legend title
        )+ # for y-axis title 
  scale_color_manual(values=c("#0072B2", "#D55E00")) # color palette


ggplot(data, aes(CONDITION, RT, colour=PREDICT)) +
  stat_summary(fun.data = mean_cl_normal,
               geom = "errorbar",
               width = 0.2,
               position = position_dodge(0.1)
  ) +
  theme_classic() +
  stat_summary(fun = mean, geom = "point", size = 3, position = position_dodge(0.1)) +
  facet_grid(cols = vars(GROUP)) +
  stat_summary(fun =mean, geom="line", size = 0.6, aes(group = PREDICT),position = position_dodge(0.1)) +
  ggtitle("Mean Reaction times in ms") +
  labs(x = "audio-video", y = "Mean Reaction Times in ms") +
  theme(axis.text.x = element_text(size = 15, angle = 20), # for x label text
        axis.title.x = element_text(size = 15), # for x axis title
        axis.title.y = element_text(size = 15), # for y-axis title 
        strip.text.x = element_text(size = 20), # for sub-title of the figure
        legend.text = element_text(size=15), # for legend size
        legend.title = element_text(size=15), # for legend title
        ) +
  scale_color_manual(values=c('#394053','#CC79A7')) # color palette


```


